// Semantic Versioning 2.0.0
//
// Actual numbers stored under subdirectory vn\*.txt files
// This file will be modified by doBuildNow.sh and will be filled in with actual version numbers - "X" characters will be removed
mgmTfA_configgv_TfAScriptVersionMajorNumber=PLEASE_RUN_DO_BUILDNOW_SCRIPT;
mgmTfA_configgv_TfAScriptVersionMinorNumber=PLEASE_RUN_DO_BUILDNOW_SCRIPT;
mgmTfA_configgv_TfAScriptVersionPatchNumber=PLEASE_RUN_DO_BUILDNOW_SCRIPT;
mgmTfA_configgv_TfAScriptVersionbuildIDNumber=PLEASE_RUN_DO_BUILDNOW_SCRIPT;
mgmTfA_configgv_TfAScriptVersionTextString=mgmTfA_configgv_TfAScriptVersionMajorNumber+"."+mgmTfA_configgv_TfAScriptVersionMinorNumber+"."+mgmTfA_configgv_TfAScriptVersionPatchNumber+".build"+mgmTfA_configgv_TfAScriptVersionbuildIDNumber;
mgmTfA_configgv_TfAScriptVersionMajorMultipliedNumber = (mgmTfA_configgv_TfAScriptVersionMajorNumber * 100);
mgmTfA_configgv_TfAScriptVersionMinorMultipliedNumber = (mgmTfA_configgv_TfAScriptVersionMinorNumber * 10);
mgmTfA_configgv_TfAScriptVersionRevisionSumValueNumber = mgmTfA_configgv_TfAScriptVersionMajorMultipliedNumber + mgmTfA_configgv_TfAScriptVersionMinorMultipliedNumber + mgmTfA_configgv_TfAScriptVersionPatchNumber;
// EOF